name: Auto Comment
on:
  issues:
    types: [opened]

jobs:
  comment:
    uses: DataScience4Psych/actions/.github/workflows/auto-comment.yml@main
    with:
      lab_number: '12'
    secrets: inherit
